const data = [
  {
    name: "card_1",
    alt: "playing_card_one",
    src: "./images/card_1.png",
    srcHidden: "./images/back.png",
    show: false,
  },
  {
    name: "card_2",
    alt: "playing_card_two",
    src: "./images/card_2.png",
    srcHidden: "./images/back.png",
    show: false,
  },
  {
    name: "card_3",
    alt: "playing_card_three",
    src: "./images/card_3.png",
    srcHidden: "./images/back.png",
    show: false,
  },
  {
    name: "card_4",
    alt: "playing_card_four",
    src: "./images/card_4.png",
    srcHidden: "./images/back.png",
    show: false,
  },
  {
    name: "card_5",
    alt: "playing_card_five",
    src: "./images/card_5.png",
    srcHidden: "./images/back.png",
    show: false,
  },
  {
    name: "card_6",
    alt: "playing_card_six",
    src: "./images/card_6.png",
    srcHidden: "./images/back.png",
    show: false,
  },
  {
    name: "card_7",
    alt: "playing_card_seven",
    src: "./images/card_7.png",
    srcHidden: "./images/back.png",
    show: false,
  },
  {
    name: "card_7",
    alt: "playing_card_eight",
    src: "./images/card_8.png",
    srcHidden: "./images/back.png",
    show: false,
  },
  {
    name: "card_9",
    alt: "playing_card_nine",
    src: "./images/card_9.png",
    srcHidden: "./images/back.png",
    show: false,
  },
  {
    name: "card_10",
    alt: "playing_card_ten",
    src: "./images/card_10.png",
    srcHidden: "./images/back.png",
    show: false,
  },
  {
    name: "card_11",
    alt: "playing_card_eleven",
    src: "./images/card_11.png",
    srcHidden: "./images/back.png",
    show: false,
  },
  {
    name: "card_12",
    alt: "playing_card_twelve",
    src: "./images/card_12.png",
    srcHidden: "./images/back.png",
    show: false,
  },
  {
    name: "card_13",
    alt: "playing_card_thirteen",
    src: "./images/card_13.png",
    srcHidden: "./images/back.png",
    show: false,
  },
  {
    name: "card_14",
    alt: "playing_card_fourteen",
    src: "./images/card_14.png",
    srcHidden: "./images/back.png",
    show: false,
  },
  {
    name: "card_15",
    alt: "playing_card_fifteen",
    src: "./images/card_15.png",
    srcHidden: "./images/back.png",
    show: false,
  },
  {
    name: "card_16",
    alt: "playing_card_sixteen",
    src: "./images/card_16.png",
    srcHidden: "./images/back.png",
    show: false,
  },
  {
    name: "card_17",
    alt: "playing_card_seventeen",
    src: "./images/card_17.png",
    srcHidden: "./images/back.png",
    show: false,
  },
  {
    name: "card_18",
    alt: "playing_card_eighteen",
    src: "./images/card_18.png",
    srcHidden: "./images/back.png",
    show: false,
  },
  {
    name: "card_19",
    alt: "playing_card_nineteen",
    src: "./images/card_19.png",
    srcHidden: "./images/back.png",
    show: false,
  },
  {
    name: "card_20",
    alt: "playing_card_twenty",
    src: "./images/card_20.png",
    srcHidden: "./images/back.png",
    show: false,
  },
  {
    name: "card_21",
    alt: "playing_card_twentyone",
    src: "./images/card_21.png",
    srcHidden: "./images/back.png",
    show: false,
  },
  {
    name: "card_22",
    alt: "playing_card_twentytwo",
    src: "./images/card_22.png",
    srcHidden: "./images/back.png",
    show: false,
  },
  {
    name: "card_23",
    alt: "playing_card_twentythree",
    src: "./images/card_23.png",
    srcHidden: "./images/back.png",
    show: false,
  },
  {
    name: "card_24",
    alt: "playing_card_twentyfour",
    src: "./images/card_24.png",
    srcHidden: "./images/back.png",
    show: false,
  },
];
